### ISSUE TITLE
Going open source?

### ISSUE THREAD

**Issue by nicolas-goudry** [YellowInnovation/sofa#1]
Shouldn’t we open source this project?

**Comment by OtaK** [comment]
There's still a bit of work left on the documentation, but when it'll be ready I'll make it public 😉

**Comment by nicolas-goudry** [comment]
Sounds good to me 👍 

Keep this open until public release 😉

**Comment by OtaK** [comment]
Opened + released at https://crates.io/crates/sofa ;)
